server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/haileypark-kr/spring-cloud-research-configs
          username: haileypark-kr
          password: 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 # private repo인 경우 github에서 personal token 생성 필요.
          
#          uri: file:///Users/soohyun/development/study/inflearn/Spring Cloud and MSA - 이도원/configs

