server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: file:///Users/soohyun/development/study/inflearn/Spring Cloud and MSA - 이도원/configs


